- name: local
  hosts: local
  become: true
  roles:
    - common

- name: k3s_cluster
  hosts: k3s_cluster
  become: true
  roles:
    - common
    - prereq

- name: k3s_master
  hosts: k3s_master
  become: true
  vars:
    k3s_ver: v1.17.4+k3s1
    k8s_dashboard_ver: v2.0.0-beta6
    # v2.0.0-rc7 doesn't work
    # fatal: [master1]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}
    # k8s_dashboard_ver: v2.0.0-rc7
  roles:
    - k3s/master

- name: k3s_slave
  hosts: k3s_slave
  become: true
  vars:
    k3s_ver: v1.17.4+k3s1
  roles:
    - k3s/node
