- name: local
  hosts: local
  become: true
  roles:
    - common

- name: k3s_cluster
  hosts: k3s_cluster
  become: true
  roles:
    - common
    - prereq

- name: k8s_master
  hosts: k8s_master
  become: true
  vars:
    k3s_ver: v1.17.4+k3s1
  roles:
    - k3s/master

- name: k8s_slave
  hosts: k8s_slave
  become: true
  vars:
    k3s_ver: v1.17.4+k3s1
  roles:
    - k3s/node
