---
- name: Update setuptools
  pip:
    name: setuptools
    extra_args: -U
- name: Ensure openshift and PyYAML modules are installed for k8s module
  pip:
    executable: /usr/bin/pip
    name: ['openshift>=0.6', 'PyYAML>=3.11']
    extra_args: --ignore-installed
- name: Download dashboard and metric server yaml
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/dashboard/{{ k8s_dashboard_ver }}/aio/deploy/recommended.yaml
    dest: /root/recommended.yaml
- name: Apply kubernetes/dashboard
  k8s:
    src: /root/recommended.yaml
    apply: yes
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
- name: copy service-account.yaml
  copy:
    src: service-account.yaml
    dest: /root/service-account.yaml
- name: Apply from service-account file
  k8s:
    src: /root/service-account.yaml
    apply: yes
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
- name: copy cluster-role.yaml
  copy:
    src: cluster-role.yaml
    dest: /root/cluster-role.yaml
- name: Apply from cluster-role file
  k8s:
    src: /root/cluster-role.yaml
    apply: yes
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
- debug:
    msg: "Copy long token string from   # kubectl -n kube-system describe secret admin-user"
- debug:
    msg: "Run port-forward on master    # kubectl port-forward -n kubernetes-dashboard service/kubernetes-dashboard 10443:443 --address 0.0.0.0"
- debug:
    msg: "Open https://{{ hostvars['master1']['ansible_facts']['fqdn'] }}:10443 and login with token"
