---
# tasks file for common
- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
- name: Install list of default packages
  yum:
    name:
      - mc
      - htop
      - unzip
      - git
      - wget
      - net-tools
    state: present
